############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "A propos"
url = "about/"
weight = 2

[[main]]
name = "Projets"
url = "projects/"
weight = 3

# footer menu
[[footer]]
name = "A propos"
url = "about/"
weight = 1
